apiVersion: v2
name: ortelius
description: Post-Deployment Vulnerability Detection and AI Remediation
home: https://ortelius.io
icon: https://ortelius.github.io/helmcharts/ortelius.svg
keywords:
- Vulnerability
- Remediation
- AI
- SBOM
type: application
version: 12.0.191
appVersion: 12.0.0
dependencies:
- name: arangodb
  version: 12.0.23
  repository: https://ortelius.github.io/arangodb/
- name: ortelius
  version: 12.0.460
  repository: https://ortelius.github.io/ortelius/
- name: frontend
  version: 12.0.1605
  repository: https://ortelius.github.io/frontend/
- name: osvdev-job
  version: 12.0.217
  repository: https://ortelius.github.io/osvdev-job/
- name: relscanner-job
  version: 12.0.233
  repository: https://ortelius.github.io/relscanner-job/
